version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
  